### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Superate
email: hello@superate.app
description: Find Influencers to promote your brand
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brands.superate.app" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: superate.hq
github_username:  superate.hq
author: Vitalik Technologies
logo: assets/images/large-logo.png
twitter:
  username: superate.hq
social:
  name: superate.hq
  # links:


languages: ["en"]
ampdir: amp

github: https://github.com/Superate-HQ

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: G-YFKV617RS0
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
